"""Refresh the stats on the profile card, then rebuild both SVGs.

The GitHub queries are adapted from Andrew Grant's (Andrew6rant) profile card
generator. What changed: stars and followers are not tracked, the contributed-repo
archive for deleted repositories is gone, 502s are retried with a smaller page,
and the SVGs are regenerated by tools/card.py rather than patched element by
element -- so the dot alignment cannot drift away from the values.
"""
import datetime
import requests
import os
import sys
import time
import hashlib

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tools'))
import card

# Fine-grained personal access token with All Repositories access:
# Account permissions: none required
# Repository permissions: read:Commit statuses, read:Contents, read:Metadata
# ACCESS_TOKEN is optional. Without it the workflow falls back to the automatic
# GITHUB_TOKEN, which can see every public repository -- enough for the whole card
# except lines of code inside private repos. An unset secret arrives as an empty
# string rather than as a missing key, hence the `or` chain rather than .get().
TOKEN = os.environ.get('ACCESS_TOKEN') or os.environ.get('GITHUB_TOKEN')
USER_NAME = os.environ.get('USER_NAME') or os.environ.get('GITHUB_REPOSITORY_OWNER')

if not TOKEN:
    raise SystemExit(
        'No token. Set the ACCESS_TOKEN secret, or run this inside GitHub Actions\n'
        'where GITHUB_TOKEN is provided automatically. Locally:\n'
        '  ACCESS_TOKEN=$(gh auth token) USER_NAME=BasilSuhail python today.py')
if not USER_NAME:
    raise SystemExit('No username. Set USER_NAME, e.g. USER_NAME=BasilSuhail.')

HEADERS = {'authorization': 'token ' + TOKEN}
QUERY_COUNT = {'user_getter': 0, 'graph_repos': 0, 'graph_contributions': 0, 'recursive_loc': 0, 'loc_query': 0}


def simple_request(func_name, query, variables):
    """
    Returns a request, or raises an Exception if the response does not succeed.
    """
    request = requests.post('https://api.github.com/graphql', json={'query': query, 'variables': variables}, headers=HEADERS)
    if request.status_code == 200:
        return request
    raise Exception(func_name, ' has failed with a', request.status_code, request.text, QUERY_COUNT)


def graph_repos(owner_affiliation):
    """
    Uses GitHub's GraphQL v4 API to return the public repository count.

    Restricted to public repositories on purpose, so the card reports the same
    figure whichever token runs it. Counting private repos would make the number
    depend on whether ACCESS_TOKEN happens to be set, and would not match what a
    visitor sees on the profile anyway.
    """
    query_count('graph_repos')
    query = '''
    query ($owner_affiliation: [RepositoryAffiliation], $login: String!) {
        user(login: $login) {
            repositories(first: 1, ownerAffiliations: $owner_affiliation, privacy: PUBLIC) {
                totalCount
            }
        }
    }'''
    variables = {'owner_affiliation': owner_affiliation, 'login': USER_NAME}
    request = simple_request(graph_repos.__name__, query, variables)
    return request.json()['data']['user']['repositories']['totalCount']


def recursive_loc(owner, repo_name, data, cache_comment, addition_total=0, deletion_total=0, my_commits=0, cursor=None):
    """
    Uses GitHub's GraphQL v4 API and cursor pagination to fetch 100 commits from a repository at a time
    """
    query_count('recursive_loc')
    query = '''
    query ($repo_name: String!, $owner: String!, $cursor: String, $page: Int!) {
        repository(name: $repo_name, owner: $owner) {
            defaultBranchRef {
                target {
                    ... on Commit {
                        history(first: $page, after: $cursor) {
                            totalCount
                            edges {
                                node {
                                    ... on Commit {
                                        committedDate
                                    }
                                    author {
                                        user {
                                            id
                                        }
                                    }
                                    deletions
                                    additions
                                }
                            }
                            pageInfo {
                                endCursor
                                hasNextPage
                            }
                        }
                    }
                }
            }
        }
    }'''
    # Repositories with long histories (large forks especially) make GitHub time
    # out and return a 502. Retry with a smaller page each time before giving up.
    request = None
    for page in (100, 50, 25, 10):
        variables = {'repo_name': repo_name, 'owner': owner, 'cursor': cursor, 'page': page}
        request = requests.post('https://api.github.com/graphql', json={'query': query, 'variables': variables}, headers=HEADERS)  # not simple_request(), because the cache file must be saved before raising
        if request.status_code == 200:
            if request.json()['data']['repository']['defaultBranchRef'] != None:  # Only count commits if repo isn't empty
                return loc_counter_one_repo(owner, repo_name, data, cache_comment, request.json()['data']['repository']['defaultBranchRef']['target']['history'], addition_total, deletion_total, my_commits)
            else:
                return 0
        if request.status_code not in (502, 503, 504):
            break
        print(f'   {owner}/{repo_name}: {request.status_code}, retrying with a page of {page // 2}')
        time.sleep(3)

    force_close_file(data, cache_comment)  # saves what is currently in the file before this program crashes
    if request.status_code == 403:
        raise Exception('Too many requests in a short amount of time!\nYou\'ve hit the non-documented anti-abuse limit!')
    raise Exception('recursive_loc() has failed with a', request.status_code, request.text, QUERY_COUNT)


def loc_counter_one_repo(owner, repo_name, data, cache_comment, history, addition_total, deletion_total, my_commits):
    """
    Recursively call recursive_loc (since GraphQL can only search 100 commits at a time)
    only adds the LOC value of commits authored by me
    """
    for node in history['edges']:
        if node['node']['author']['user'] == OWNER_ID:
            my_commits += 1
            addition_total += node['node']['additions']
            deletion_total += node['node']['deletions']

    if history['edges'] == [] or not history['pageInfo']['hasNextPage']:
        return addition_total, deletion_total, my_commits
    else:
        return recursive_loc(owner, repo_name, data, cache_comment, addition_total, deletion_total, my_commits, history['pageInfo']['endCursor'])


def loc_query(owner_affiliation, comment_size=0, force_cache=False, cursor=None, edges=[]):
    """
    Uses GitHub's GraphQL v4 API to query all the repositories I have access to (with respect to owner_affiliation)
    Queries 60 repos at a time, because larger queries give a 502 timeout error and smaller queries send too many
    requests and also give a 502 error.
    Returns the total number of lines of code in all repositories
    """
    query_count('loc_query')
    query = '''
    query ($owner_affiliation: [RepositoryAffiliation], $login: String!, $cursor: String) {
        user(login: $login) {
            repositories(first: 60, after: $cursor, ownerAffiliations: $owner_affiliation, privacy: PUBLIC) {
            edges {
                node {
                    ... on Repository {
                        nameWithOwner
                        defaultBranchRef {
                            target {
                                ... on Commit {
                                    history {
                                        totalCount
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                pageInfo {
                    endCursor
                    hasNextPage
                }
            }
        }
    }'''
    variables = {'owner_affiliation': owner_affiliation, 'login': USER_NAME, 'cursor': cursor}
    request = simple_request(loc_query.__name__, query, variables)
    if request.json()['data']['user']['repositories']['pageInfo']['hasNextPage']:   # If repository data has another page
        edges += request.json()['data']['user']['repositories']['edges']            # Add on to the LoC count
        return loc_query(owner_affiliation, comment_size, force_cache, request.json()['data']['user']['repositories']['pageInfo']['endCursor'], edges)
    else:
        return cache_builder(edges + request.json()['data']['user']['repositories']['edges'], comment_size, force_cache)


def cache_builder(edges, comment_size, force_cache, loc_add=0, loc_del=0):
    """
    Checks each repository in edges to see if it has been updated since the last time it was cached
    If it has, run recursive_loc on that repository to update the LOC count
    """
    cached = True  # Assume all repositories are cached
    filename = 'cache/' + hashlib.sha256(USER_NAME.encode('utf-8')).hexdigest() + '.txt'  # Create a unique filename for each user
    try:
        with open(filename, 'r') as f:
            data = f.readlines()
    except FileNotFoundError:  # If the cache file doesn't exist, create it
        data = []
        if comment_size > 0:
            for _ in range(comment_size):
                data.append('This line is a comment block. Write whatever you want here.\n')
        with open(filename, 'w') as f:
            f.writelines(data)

    if len(data) - comment_size != len(edges) or force_cache:  # If the number of repos has changed, or force_cache is True
        cached = False
        flush_cache(edges, filename, comment_size)
        with open(filename, 'r') as f:
            data = f.readlines()

    cache_comment = data[:comment_size]  # save the comment block
    data = data[comment_size:]  # remove those lines
    for index in range(len(edges)):
        repo_hash, commit_count, *__ = data[index].split()
        if repo_hash == hashlib.sha256(edges[index]['node']['nameWithOwner'].encode('utf-8')).hexdigest():
            try:
                if int(commit_count) != edges[index]['node']['defaultBranchRef']['target']['history']['totalCount']:
                    # if commit count has changed, update loc for that repo
                    owner, repo_name = edges[index]['node']['nameWithOwner'].split('/')
                    loc = recursive_loc(owner, repo_name, data, cache_comment)
                    data[index] = repo_hash + ' ' + str(edges[index]['node']['defaultBranchRef']['target']['history']['totalCount']) + ' ' + str(loc[2]) + ' ' + str(loc[0]) + ' ' + str(loc[1]) + '\n'
            except TypeError:  # If the repo is empty
                data[index] = repo_hash + ' 0 0 0 0\n'
    with open(filename, 'w') as f:
        f.writelines(cache_comment)
        f.writelines(data)
    for line in data:
        loc = line.split()
        loc_add += int(loc[3])
        loc_del += int(loc[4])
    return [loc_add, loc_del, loc_add - loc_del, cached]


def flush_cache(edges, filename, comment_size):
    """
    Wipes the cache file
    This is called when the number of repositories changes or when the file is first created
    """
    with open(filename, 'r') as f:
        data = []
        if comment_size > 0:
            data = f.readlines()[:comment_size]  # only save the comment
    with open(filename, 'w') as f:
        f.writelines(data)
        for node in edges:
            f.write(hashlib.sha256(node['node']['nameWithOwner'].encode('utf-8')).hexdigest() + ' 0 0 0 0\n')


def force_close_file(data, cache_comment):
    """
    Forces the file to close, preserving whatever data was written to it
    This is needed because if this function is called, the program would've crashed before the file is properly saved and closed
    """
    filename = 'cache/' + hashlib.sha256(USER_NAME.encode('utf-8')).hexdigest() + '.txt'
    with open(filename, 'w') as f:
        f.writelines(cache_comment)
        f.writelines(data)
    print('There was an error while writing to the cache file. The file,', filename, 'has had the partial data saved and closed.')


def graph_contributions(created_at):
    """
    Total contributions since the account was created, the same number the
    profile's contribution graph shows: commits plus pull requests, issues and
    reviews, forks excluded. The calendar can only be queried a year at a time.

    Counted against whichever token is in use, so private contributions only
    appear when ACCESS_TOKEN is a PAT belonging to this user.
    """
    query = '''
    query($login: String!, $from: DateTime!, $to: DateTime!) {
        user(login: $login) {
            contributionsCollection(from: $from, to: $to) {
                contributionCalendar {
                    totalContributions
                }
            }
        }
    }'''
    start = datetime.datetime.strptime(created_at, '%Y-%m-%dT%H:%M:%SZ')
    today = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
    total = 0
    for year in range(start.year, today.year + 1):
        window_start = max(start, datetime.datetime(year, 1, 1))
        window_end = min(today, datetime.datetime(year, 12, 31, 23, 59, 59))
        if window_start >= window_end:
            continue
        query_count('graph_contributions')
        variables = {'login': USER_NAME,
                     'from': window_start.strftime('%Y-%m-%dT%H:%M:%SZ'),
                     'to': window_end.strftime('%Y-%m-%dT%H:%M:%SZ')}
        request = simple_request(graph_contributions.__name__, query, variables)
        total += request.json()['data']['user']['contributionsCollection']['contributionCalendar']['totalContributions']
    return total


def user_getter(username):
    """
    Returns the account ID and creation date of the user
    """
    query_count('user_getter')
    query = '''
    query($login: String!){
        user(login: $login) {
            id
            createdAt
        }
    }'''
    variables = {'login': username}
    request = simple_request(user_getter.__name__, query, variables)
    return {'id': request.json()['data']['user']['id']}, request.json()['data']['user']['createdAt']


def query_count(funct_id):
    """
    Counts how many times the GitHub GraphQL API is called
    """
    global QUERY_COUNT
    QUERY_COUNT[funct_id] += 1


def perf_counter(funct, *args):
    """
    Calculates the time it takes for a function to run
    Returns the function result and the time differential
    """
    start = time.perf_counter()
    funct_return = funct(*args)
    return funct_return, time.perf_counter() - start


def formatter(query_type, difference, funct_return=False, whitespace=0):
    """
    Prints a formatted time differential
    Returns formatted result if whitespace is specified, otherwise returns raw result
    """
    print('{:<23}'.format('   ' + query_type + ':'), sep='', end='')
    print('{:>12}'.format('%.4f' % difference + ' s ')) if difference > 1 else print('{:>12}'.format('%.4f' % (difference * 1000) + ' ms'))
    if whitespace:
        return f"{'{:,}'.format(funct_return): <{whitespace}}"
    return funct_return


if __name__ == '__main__':
    """
    Basil Suhail (BasilSuhail), 2026
    Card mechanics adapted from Andrew Grant (Andrew6rant), 2022-2025
    """
    print('Calculation times:')
    user_data, user_time = perf_counter(user_getter, USER_NAME)
    OWNER_ID, created_at = user_data
    formatter('account data', user_time)
    total_loc, loc_time = perf_counter(loc_query, ['OWNER', 'COLLABORATOR', 'ORGANIZATION_MEMBER'], 7)
    formatter('LOC (cached)', loc_time) if total_loc[-1] else formatter('LOC (no cache)', loc_time)
    contrib_commits, contrib_commits_time = perf_counter(graph_contributions, created_at)
    formatter('contributions', contrib_commits_time)
    repo_data, repo_time = perf_counter(graph_repos, ['OWNER'])
    formatter('my repositories', repo_time)
    contrib_data, contrib_time = perf_counter(graph_repos, ['OWNER', 'COLLABORATOR', 'ORGANIZATION_MEMBER'])
    formatter('contributed repos', contrib_time)

    for index in range(len(total_loc) - 1):
        total_loc[index] = '{:,}'.format(total_loc[index])  # format added, deleted, and total LOC

    for path in card.render({
        'repos': '{:,}'.format(repo_data),
        'contrib': '{:,}'.format(contrib_data),
        'contributions': '{:,}'.format(contrib_commits),
        'loc': total_loc[2],
        'loc_add': total_loc[0],
        'loc_del': total_loc[1],
    }):
        print('   wrote', os.path.basename(path))

    print('Total GitHub GraphQL API calls:', '{:>3}'.format(sum(QUERY_COUNT.values())))
    for funct_name, count in QUERY_COUNT.items():
        print('{:<28}'.format('   ' + funct_name + ':'), '{:>6}'.format(count))
